START_SATIETI = 60
START_HAPPINES = 60
START_MONEY = 50

MAX_HAPPINES = 100
MAX_SATIETI = 100
MIN_HAPPINES = 0
MIN_SATIETI = 0

SATIETI_STEP_EAT = 50
HAPPINES_STEP_EAT = 20
FOOD_STEP_EAT = 20

HAPPINES_STEP_SLEEP = 50
SATIETI_STEP_SLEEP = 20

MONEY_STEP_WORK = 100
HAPPINES_STEP_WORK = 40

HAPPINES_STEP_PLAY = 60
SATIETI_STEP_PLAY = 20

MAN_FOOD_COST = 100
CAT_FOOD_COST = 50
CAT_FOOD_STEP_STORE = 50
MAN_FOOD_STEP_STORE = 100
SATIETI_STEP_STORE = 20
HAPPINES_STEP_STORE = 20
MONEY_STEP_STORE = 70

MAN_FOOD_STEP_MALL = 150
CAT_FOOD_STEP_MALL = 150
MAN_FOOD_COST_MALL = 100
CAT_FOOD_COST_MALL = 100

LIVE_MIN_HAPPINES = 40
LIVE_MIN_SATIETI = 40
LIVE_EAT_FOOD = 20
LIVE_MIN_MONEY_MALL = 300
LIVE_EAT_MONEY = 50
LIVE_MIN_MONEY = 40
LIVE_MIN_MONEY_CAT = 10
LIVE_MIN_MAN_FOOD = 40
LIVE_MIN_CAT_FOOD = 40
LIVE_MIN_HOME_CAT_FOOD = 20

HAPPINES_STEP_GROW_UP = 50
GROW_STEP = 1

HAPPINES_STEP_BURY_CAT = 30

HAPPINES_STEP_FEED_CAT = 20
SATIETI_STEP_FEED_CAT = 20
FOOD_STEP_FEED_CAT = 20

CAT_COST = 400
MONEY_FOR_BUY_CAT = 500
HAPPINES_STEP_BUY_CAT = 40

BUY_FLOWERS_HAPPINESS_STEP = 30
BUY_FLOWERS_MONEY_STEP = 20
